countries_dict = {
    "Afganistan": "Afghanistan",
    "Albania": "Albania",
    "Algieria": "Algeria",
    "Andora": "Andorra",
    "Angola": "Angola",
    "Antigua i Barbuda": "Antigua and Barbuda",
    "Arabia Saudyjska": "Saudi Arabia",
    "Argentyna": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbejdżan": "Azerbaijan",
    "Bahamy": "Bahamas",
    "Bahrajn": "Bahrain",
    "Bangladesz": "Bangladesh",
    "Barbados": "Barbados",
    "Białoruś": "Belarus",
    "Belgia": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Boliwia": "Bolivia",
    "Bośnia i Hercegowina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazylia": "Brazil",
    "Brunei": "Brunei",
    "Bułgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Chiny": "China",
    "Chorwacja": "Croatia",
    "Cypr": "Cyprus",
    "Czechy": "Czechia",
    "Dania": "Denmark",
    "Dominika": "Dominica",
    "Dominikana": "Dominican Republic",
    "Dżibuti": "Djibouti",
    "Egipt": "Egypt",
    "Ekwador": "Ecuador",
    "Erytrea": "Eritrea",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Etiopia": "Ethiopia",
    "Fidżi": "Fiji",
    "Filipiny": "Philippines",
    "Finlandia": "Finland",
    "Francja": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Grecja": "Greece",
    "Grenada": "Grenada",
    "Gwatemala": "Guatemala",
    "Gwinea": "Guinea",
    "Gwinea Bissau": "Guinea-Bissau",
    "Gwinea Równikowa": "Equatorial Guinea",
    "Haiti": "Haiti",
    "Hiszpania": "Spain",
    "Holandia": "Netherlands",
    "Honduras": "Honduras",
    "Indie": "India",
    "Indonezja": "Indonesia",
    "Irak": "Iraq",
    "Iran": "Iran",
    "Irlandia": "Ireland",
    "Islandia": "Iceland",
    "Izrael": "Israel",
    "Jamajka": "Jamaica",
    "Japonia": "Japan",
    "Jemen": "Yemen",
    "Jordania": "Jordan",
    "Kanada": "Canada",
    "Katar": "Qatar",
    "Kazachstan": "Kazakhstan",
    "Kenia": "Kenya",
    "Kambodża": "Cambodia",
    "Kamerun": "Cameroon",
    "Karaiby": "Caribbean",
    "Kirgistan": "Kyrgyzstan",
    "Korea Południowa": "South Korea",
    "Korea Północna": "North Korea",
    "Kostaryka": "Costa Rica",
    "Kuba": "Cuba",
    "Kuwejt": "Kuwait",
    "Laos": "Laos",
    "Lesotho": "Lesotho",
    "Liban": "Lebanon",
    "Liberia": "Liberia",
    "Libia": "Libya",
    "Lichtenstein": "Liechtenstein",
    "Litwa": "Lithuania",
    "Luksemburg": "Luxembourg",
    "Łotwa": "Latvia",
    "Malawi": "Malawi",
    "Malaje": "Malaysia",
    "Malediwy": "Maldives",
    "Malta": "Malta",
    "Maroko": "Morocco",
    "Maurycjusz": "Mauritius",
    "Mauritania": "Mauritania",
    "Meksyk": "Mexico",
    "Mołdawia": "Moldova",
    "Monako": "Monaco",
    "Mongolia": "Mongolia",
    "Mozambik": "Mozambique",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "Niemcy": "Germany",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Norwegia": "Norway",
    "Nowa Zelandia": "New Zealand",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Papua-Nowa Gwinea": "Papua New Guinea",
    "Paragwaj": "Paraguay",
    "Peru": "Peru",
    "Polska": "Poland",
    "Portugalia": "Portugal",
    "Rosja": "Russia",
    "Rumunia": "Romania",
    "Rwanda": "Rwanda",
    "Saint Kitts i Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent i Grenadyny": "Saint Vincent and the Grenadines",
    "Sambia": "Zambia",
    "Sahara Zachodnia": "Western Sahara",
    "Sao Tome i Principe": "Sao Tome and Principe",
    "Seychely": "Seychelles",
    "Singapur": "Singapore",
    "Słowacja": "Slovakia",
    "Słowenia": "Slovenia",
    "Somalia": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "Stany Zjednoczone": "United States",
    "Suazi": "Swaziland",
    "Szwajcaria": "Switzerland",
    "Szwecja": "Sweden",
    "Tadżykistan": "Tajikistan",
    "Tajlandia": "Thailand",
    "Tajwan": "Taiwan",
    "Tanzania": "Tanzania",
    "Timor Wschodni": "East Timor",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad i Tobago": "Trinidad and Tobago",
    "Tunezja": "Tunisia",
    "Turcja": "Turkey",
    "Uganda": "Uganda",
    "Ukraina": "Ukraine",
    "Urugwaj": "Uruguay",
    "Watykan": "Vatican",
    "Wenezuela": "Venezuela",
    "Wielka Brytania": "United Kingdom",
    "Włochy": "Italy",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
}
