countries_polish = [
    "Afganistan",
    "Albania",
    "Algieria",
    "Andora",
    "Angola",
    "Antigua i Barbuda",
    "Arabia Saudyjska",
    "Argentyna",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbejdżan",
    "Bahamy",
    "Bahrajn",
    "Bangladesz",
    "Barbados",
    "Białoruś",
    "Belgia",
    "Belize",
    "Benin",
    "Bhutan",
    "Boliwia",
    "Bośnia i Hercegowina",
    "Botswana",
    "Brazylia",
    "Brunei",
    "Bułgaria",
    "Burkina Faso",
    "Burundi",
    "Chiny",
    "Chorwacja",
    "Cypr",
    "Czechy",
    "Dania",
    "Dominika",
    "Dominikana",
    "Dżibuti",
    "Egipt",
    "Ekwador",
    "Erytrea",
    "Estonia",
    "Eswatini",
    "Etiopia",
    "Fidżi",
    "Filipiny",
    "Finlandia",
    "Francja",
    "Gabon",
    "Gambia",
    "Georgia",
    "Ghana",
    "Grecja",
    "Grenada",
    "Gwatemala",
    "Gwinea",
    "Gwinea Bissau",
    "Gwinea Równikowa",
    "Haiti",
    "Hiszpania",
    "Holandia",
    "Honduras",
    "Indie",
    "Indonezja",
    "Irak",
    "Iran",
    "Irlandia",
    "Islandia",
    "Izrael",
    "Jamajka",
    "Japonia",
    "Jemen",
    "Jordania",
    "Kanada",
    "Katar",
    "Kazachstan",
    "Kenia",
    "Kambodża",
    "Kamerun",
    "Karaiby",
    "Katar",
    "Kazachstan",
    "Kenia",
    "Kirgistan",
    "Korea Południowa",
    "Korea Północna",
    "Kostaryka",
    "Kuba",
    "Kuwejt",
    "Laos",
    "Lesotho",
    "Liban",
    "Liberia",
    "Libia",
    "Lichtenstein",
    "Litwa",
    "Luksemburg",
    "Łotwa",
    "Malawi",
    "Malaje",
    "Malediwy",
    "Malta",
    "Maroko",
    "Maurycjusz",
    "Mauritania",
    "Meksyk",
    "Mołdawia",
    "Monako",
    "Mongolia",
    "Mozambik",
    "Namibia",
    "Nepal",
    "Niemcy",
    "Niger",
    "Nigeria",
    "Norwegia",
    "Nowa Zelandia",
    "Oman",
    "Pakistan",
    "Panama",
    "Papua-Nowa Gwinea",
    "Paragwaj",
    "Peru",
    "Polska",
    "Portugalia",
    "Rosja",
    "Rwanda",
    "Rumunia",
    "Rwanda",
    "Saint Kitts i Nevis",
    "Saint Lucia",
    "Saint Vincent i Grenadyny",
    "Sambia",
    "Sahara Zachodnia",
    "Sao Tome i Principe",
    "Arabia Saudyjska",
    "Seychely",
    "Singapur",
    "Słowacja",
    "Słowenia",
    "Smalaj",
    "Somalia",
    "Sri Lanka",
    "Stany Zjednoczone",
    "Suazi",
    "Szwajcaria",
    "Szwecja",
    "Tadżykistan",
    "Tajlandia",
    "Tajwan",
    "Tanzania",
    "Timor Wschodni",
    "Togo",
    "Tonga",
    "Trinidad i Tobago",
    "Tunezja",
    "Turcja",
    "Uganda",
    "Ukraina",
    "Urugwaj",
    "Watykan",
    "Wenezuela",
    "Wielka Brytania",
    "Włochy",
    "Zambia",
    "Zimbabwe"
]
